name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GH_REF: ${{ (github.event.pull_request.merged && github.event.pull_request.base.ref) || github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ env.GH_REF }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Run Generate css
        run: yarn generate:css

      - name: Run ESLint
        run: yarn lint:ci

      - name: Run Tests
        run: yarn test
